# This is patty's config file.
# Refer to the wiki for more information.
# https://wiki.hyprland.org/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = ghostty
$fileManager = dolphin
$menu = wofi --show drun
$internetBrowser = firefox

################
### MONITORS ###
################
source = ~/dotfiles/hypr/conf/monitor.conf

#################
### AUTOSTART ###
#################
source = ~/dotfiles/hypr/conf/autostart.conf
source = ~/dotfiles/hypr/conf/cursor.conf
source = ~/dotfiles/hypr/conf/environments.conf

#############
### INPUT ###
#############
source = ~/dotfiles/hypr/conf/input.conf 

###################
### KEYBINDINGS ###
###################
source = ~/dotfiles/hypr/conf/binds.conf 

##############################
### WINDOWS AND WORKSPACES ###
##############################
source = ~/dotfiles/hypr/conf/windowrules.conf

