# See https://wiki.hyprland.org/Configuring/Monitors/
#monitor= , preferred, auto, 1
monitor=desc:LG Electronics LG ULTRAGEAR 103NTRLJF726,2560x1440@144,-2560x0,1
monitor=desc:LG Electronics LG ULTRAGEAR 407MXSK10694,2560x1440@165,0x0,1
