# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
# TODO: Check Hyprland 0.53 wiki for correct suppressevent syntax
# windowrule = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland  
# TODO: Check Hyprland 0.53 wiki for correct focus/nofocus syntax
# windowrule = focus 0, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0
# TODO: Check if workspace assignment should use workspace rules instead
# windowrule = workspace 5, class:^steam_app_\d+$
workspace = 5, border:false, rounding:false
windowrule = opacity 0.9 0.9, match:class cursor
